version: '3.9'

services:
  postgres-marmut:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=azka
      - POSTGRES_USER=azka
      - POSTGRES_DB=marmut